### ISSUE TITLE
Avoid repetitive languages?

### ISSUE THREAD

**Issue by m-mohr** [padarom/vuepress-plugin-code-switcher#5]
So, we'll have a lot of code switches soon and we always have the same 3 languages, so to each CodeSwitcher we need to pass:

` :languages="{py:'Python', r:'R', js:'JavaScript'}"`

That is very repetitive. Is there a way to avoid that and set them globally? For example, through setting them in the plugin config? So instead of `'code-switcher'` use `['code-switcher', {py:'Python', r:'R', js:'JavaScript'}]`?

**Comment by padarom** [comment]
That's a good idea. I don't know if I have much time at the moment, but I'll give something like this a try soon

**Comment by m-mohr** [comment]
Thanks a lot, @padarom! It is  even more than I had in mind.

I've tested this branch and it works for me.
